### ISSUE TITLE
install deps error getDefaultHighWaterMark

### ISSUE THREAD

**Issue by PhE** [nuxt-ui-pro/saas#13]
The setup of the template raises the error :
```
 ERROR  The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark'

  import {PassThrough as PassThroughStream, getDefaultHighWaterMark} from 'node:stream';
  ^^^^^^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5) 

 ERROR  The requested module 'node:stream' does not provide an export named 'getDefaultHighWaterMark' 

 1418 packages installed [22.37s]

 ERROR  Error: Command failed with exit code 1: bun install       
```

It occurs while bootstraping a new project with:
```
npx nuxi init -t github:nuxt-ui-pro/saas
```
and choosing bun as the package manager.

It also occurs with a fresh git clone :
```
git clone git@github.com:nuxt-ui-pro/saas.git
cd saas
npx bun install
```

**Comment by PhE** [comment]
Same error with `npm` and 'yarn'  package managers.

**Comment by talhaqamar** [comment]
Have to tried upgrading the node version on the project to the latest one? I was facing same problem when using node 18.15 version. After upgrading it to the latest fixes the issue.

**Comment by ElijahBus** [comment]
A node version upgrade just fixed it for me 👍

**Comment by dev-hayash** [comment]
I also changed the version of node.js and it worked correctly.
I ran `nvm use 18.17.0`

**Comment by davision** [comment]
I had this issue out of the sudden when building Nuxt static page on Github Action. Update of node to `18.17.0` worked as well. Thanks!

**Comment by benjamincanac** [comment]
Node.js 16 has reached official end of life on September 11 2023, it is highly recommended to update to the latest LTS release (Node.js 18): https://nuxt.com/docs/getting-started/installation#new-project
