### ISSUE TITLE
Page jumps when you click on a link

### ISSUE THREAD

**Issue by gkTim** [nuxt-ui-pro/saas#19]
Hi,

first at all, great template! Love it!

I have found one behaviour which is not so nice, the page jumps to the top when you navigate a link and nagivates after that.
Its a small thing but could lead to confusion for users with small connections.

**Steps to reproduce:**

1. Open the page and scroll down.
2. Click on a link e.g. the "Buy now" button or the "Signup"-Button in the header.

**Current Behaviour:**

Page jumps to the top and navigates after that.

**Expected Behaviour:**

Page navigates to the new link and reset to to after that with no animation.

I have tested it on Chrome and Safari

**Comment by benjamincanac** [comment]
This is the default behaviour of the `app/router.options.ts` provided by `@nuxt/ui-pro`. Since the https://github.com/nuxt/ui-pro/releases/tag/v1.1.0 release, you can disable this behaviour and handle it manually:

```ts
export default defineNuxtConfig({
  uiPro: {
    routerOptions: false
  }
})
```
