### ISSUE TITLE
In a UBlogPost, is it possible to add author's name next to their image?

### ISSUE THREAD

**Issue by robmontesinos** [nuxt-ui-pro/saas#29]
I'm assuming that one way to do this is to copy BlogPost into components folder and rename it to UBlogPost and add a slot for author's name. 

I'd appreciate it if someone could share a better way to make this modification - the blog author's name is pretty important for this part of this project as well as other projects.

Thank you in advance.

**Comment by benjamincanac** [comment]
You can use the `#authors` slot to display what you want instead of the default `UAvatarGroup`.

**Comment by robmontesinos** [comment]
Thank you @benjamincanac - I will try it out and post my reaction to your quick response - have a great weekend

**Comment by robmontesinos** [comment]
You were correct @benjamincanac and I appreciate it. With the slight modification of adding the <template #authors></template> slot as you suggested, it opened a whole bunch of styling possibilities, including additions to the UI object. Thank you again and I'm closing this note out.
