### ISSUE TITLE
feat(eslint): add `eslint-plugin-tailwindcss`

### ISSUE THREAD

**Issue by shinGangan** [nuxt-ui-pro/saas#41]
### ✋ Context

Nuxt UI is implemented based on Tailwind CSS. 
Therefore, it can benefit from [eslint-plugin-tailwindcss](https://github.com/francoismassart/eslint-plugin-tailwindcss).

Users who use this template will need to configure ESLint's findings themselves later.(I added it in my personal repo already)

So, how about adding the settings as a template?

**Comment by benjamincanac** [comment]
I agree this could be a nice addition but I'm not sure I want to enforce this when creating a new project. I like the idea of having the eslint module by default and then people can add their own plugin.

**Comment by shinGangan** [comment]
Well, I had a similar opinion, so I asked the question in an issue rather than a PR.

I support this opinion and will close this issue. Thank you for your answer.
