### ISSUE TITLE
Proposal to improve Accessibility

### ISSUE THREAD

**Issue by LutherApp** [nuxt-ui-pro/saas#61]
# Improve Accessibility with 1%
<img width="419" alt="image" src="https://github.com/user-attachments/assets/34a31280-e128-4c36-8abb-929c0a9bb58d">

## Solution
Change `blog/[slug].vue`:
<img width="292" alt="image" src="https://github.com/user-attachments/assets/b7491244-98e8-4d1e-8d9f-01fa6cf7c83e">

## Source
https://dequeuniversity.com/rules/axe/4.8/image-redundant-alt

**Comment by benjamincanac** [comment]
Thanks for the report 😊
