### ISSUE TITLE
bug: `Cannot read properties of undefined (reading 'remove')`

### ISSUE THREAD

**Issue by robingenz** [nuxt-ui-pro/saas#9]
I get the following error in the Dev Console when I navigate to `/docs/getting-started` for example:

![grafik](https://github.com/nuxt-ui-pro/saas/assets/13857929/5f3e31d7-d683-44c7-8f7a-6b496a92d3b7)

**Steps to reproduce the issue:**

1. Clone https://github.com/nuxt-ui-pro/saas
2. Run `npm install`
3. Run `npm run dev`
4. Navigate to `/docs/getting-started`

**Comment by benjamincanac** [comment]
I've noticed this too, this might have to be fixed upstream in `unhead`. I'm transferring this to `nuxt/ui-pro` repository.

**Comment by xdavidoff** [comment]
Same bug
clean instalation, after build and preview have a this error.
<img width="1480" alt="Snímek obrazovky 2024-03-01 v 19 55 14" src="https://github.com/nuxt-ui-pro/saas/assets/37173781/2ba59c06-82b4-4fa7-9e45-d694d25b720e">

**Comment by harlan-zw** [comment]
This should no longer throw an error in v1.8.11 of Unhead

**Comment by Atinux** [comment]
cc @benjamincanac

**Comment by linuxcz** [comment]
Just add in package json 
  "resolutions": {
    "@unhead/dom": "^1.8.11",
    "@unhead/ssr": "^1.8.11",
    "@unhead/vue": "^1.8.11"
  },
  And wait for fix
